### ISSUE TITLE
Todo, Edit, and Delete path forward

### ISSUE THREAD

**Issue by stroupaloop** [michael-balint/sms-todo#7]
- [x] identify the structure of the todo, current recommendation:
  - [x] keywords
  - [x] relations (actions)
  - [x] taxonomy
  - [x] date (optional)
  - [x] time (optional)
  - [x] ~~qty (optional)~~
  - [x] ~~importance?~~
- [x] identify the best way to parse this information (NLP vs tiered questions)
- [x] how to list all todos (requires [Query and Search](http://docs.aws.amazon.com/amazondynamodb/latest/gettingstartedguide/GettingStarted.NodeJs.04.html) against DynamoDB and indexing)
- [ ] figure out how to Edit a todo (using an index of some kind?)
- [x] figure out how to Delete a todo (using an index of some kind?)

NLP API options: (http://www.programmableweb.com/news/how-5-natural-language-processing-apis-stack/analysis/2014/07/28)
- http://www.alchemyapi.com/developers
- http://aylien.com/text-api
- https://www.meaningcloud.com/products
- https://www.textrazor.com/docs/rest

**Comment by stroupaloop** [comment]
- using AlchemyAPI
- don't have a solution for parsing out quantity and dates/times from AlchemyAPI
- currently list all todos vs 'paginated' version
- holding off on Edit functionality until quantity and date/time is resolved (the only things that should be editable)

**Comment by stroupaloop** [comment]
For quantity and date/time parsing > possibly add Stanford NLP library using this (https://www.npmjs.com/package/stanford-simple-nlp), may need help setting it up
